set nocompatible " Manage as ViM instead of Vi
syn on " Use syntaxic coloration
set background=dark

set softtabstop=2 " Use space as tab, eq to st
set tabstop=2 " as above, eq to ts
set textwidth=0 " as above, eq to tw
set ignorecase " eq to ic
set number " Display line number
set expandtab " Replace tab by spaces

" Manage incremental search
set incsearch
set showmatch
set hlsearch

" invisible char
nmap <leader>l :set list!<CR>
" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬
highlight NonText guifg=#9797a9
highlight SpecialKey guifg=#9797a9

" Keep the cursor in place while joining limes
nnoremap J mzJ`z

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*

" Pathogen
" Pathogen allow to manage vim plugins
" execute pathogen#infect()

